### PR TITLE
Bump GitHub Actions dependencies; add dependabot

### LINKED ISSUE #8: [Security] Workflow all-contributors.yml is using vulnerable action actions/checkout
The workflow all-contributors.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

### LINKED ISSUE #9: [Security] Workflow ci.yml is using vulnerable action actions/checkout
The workflow ci.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

### PR DESCRIPTION
**Pull request by ChrisCarini**
Fixes #8 
Fixes #9

### CODE REVIEW

**Comment by krzkaczor** [comment]
@ChrisCarini this is not maintained anymore. Please switch to your own fork.

**Comment by ChrisCarini** [comment]
> @ChrisCarini this is not maintained anymore. Please switch to your own fork.

Bummer to hear - are you open to a PR for the `README.md` to make others aware that this action is no longer maintained? If so, happy to post one..

**Comment by krzkaczor** [comment]
@ChrisCarini Yes, sure.

**Comment by ChrisCarini** [comment]
@krzkaczor sorry for delay; PR to add note about this repo not being maintained here -> https://github.com/ActionwareIO/all-contributors-action/pull/12

Please consider archiving the repo once ^ PR is merged so that is is more obvious/apparent to folks.

And, thank you for originally authoring this action, and maintaining it for the period you did! 👏

**Comment by krzkaczor** [comment]
@ChrisCarini Thanks!

**Pull request closed without merging**
